### ISSUE TITLE
missing columns

### ISSUE THREAD

**Issue by stomioka** [mdcollab/covidclinicaldata#1]
Thank you for sharing the clinical data. I am curious if you plan to add columns from the clinical lab, concomitant medications/therapy, complications, and the final disposition.

**Comment by realdjpardis** [comment]
Hi Sam, as an outpatient healthcare facility we do not have data for extended labs, medications, complications, and outcomes. We provide a template to encourage that inpatient facilities share their data and are looking for ways to connect with their teams.

**Comment by stomioka** [comment]
Thank you Pardis. I got it.
