### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by amitbcp** [mdcollab/covidclinicaldata#14]
Thanks for the open sourcing the research and clinical data.
For my research I was trying to use both clinical data with X-rays to model. And I was not able to located the X-rays in the repository nor on websites.

Can you please guide to get the X-rays for the mentioned clinical data?
Thanks in Advance !

**Comment by realdjpardis** [comment]
Only a small percentage of the patients have an associated x-ray available. You can see our fill rates on covidclinicaldata.org. 
When available you can see the links under the `cxr_link` field.
