### ISSUE TITLE
Adding more attributes related to blood test

### ISSUE THREAD

**Issue by awalece04ku** [mdcollab/covidclinicaldata#18]
Dear Curator

Can you please add some blood test results e.g., platelets, lymhocityes etc. with the data as blood results have impacts on COVID 19. I am planning to use this data.
many thanks in advance.

**Comment by realdjpardis** [comment]
We don't run blood tests for most of our patients, however, we will look up the fill rates and consider adding it to our repository. Note that these tests are usually run at inpatient facilities.
