### ISSUE TITLE
Adding Gender, BMI, ... to the dataset ?

### ISSUE THREAD

**Issue by OmKoren** [mdcollab/covidclinicaldata#2]
Hi, great work!
Have you thought of adding some more background attributes of the patients?
Specifically, I think that gender, BMI & region of residence might assist (can be used for control/stratification).
I'm not totally familiar with HIPAA but perhaps noise adding or hashing of some of those attributes can be sufficient for anonymization?

Thanks!

**Comment by realdjpardis** [comment]
We didn't see any conclusive studies regarding the association of gender with viral disease outcomes or prevalence. Region does affect prevalence however we are only allowed to provide data at the state level. BMI is a good point and we can look into it.

**Comment by OmKoren** [comment]
I did see gender association evidences (don't know about their conclusiveness). For example, in this publication, the logistic regression that the authors published did include Gender. 
![image](https://user-images.githubusercontent.com/17431695/82376019-26e3f900-9a2a-11ea-8245-8e5d0d2bc0fd.png)

https://www.nature.com/articles/s41591-020-0916-2
