### ISSUE TITLE
Difference between test types

### ISSUE THREAD

**Issue by OmKoren** [mdcollab/covidclinicaldata#3]
It appears that the dataset contains four different test types ("test_name" field):
SARS COV 2 RNA RTPCR
SARS CoV w/CoV 2 RNA
SARS-CoV-2, NAA
Rapid COVID-19 Test

However, I think that the dictionary does not explain the difference between the four.
Perhaps adding an explanation to the dictionary can assist.
Do different test-types perform differently? (sensitivity-specificity wise)

Thanks!!

**Comment by realdjpardis** [comment]
This is a great question. 

The first three are the same test (with identical sensitivity-specificity values) but from different companies. The last one, the rapid test is not like the others. The reason why we didn't squash the first three to the same value was to differentiate between the various companies without actually providing the company name for privacy reasons. Please let me know if this makes sense or if you have any recommendations.

I will add this explanation on the website.

**Comment by OmKoren** [comment]
It makes total sense. Thank you for the explanation!
