### ISSUE TITLE
Missing values - specifically in patient-reported symptoms

### ISSUE THREAD

**Issue by OmKoren** [mdcollab/covidclinicaldata#4]
Patient-reported symptoms attributes contain many missing values.
Some symptoms even have "mostly missing" values (loss of taste/smell, diarrhea, sore throat, etc).
Fever, sob, cough also have many missing values.
I wonder if this can be corrected or explained somehow. With such a high volume of missing values most imputation methods (at least the ones that I'm familiar with) aren't really helpful.

Some of those symptoms were found to be highly correlated with COVID-19, for example in this study:
https://www.nature.com/articles/s41591-020-0916-2

So I guess I wonder if there is any plan/hints to make those attributes more complete.

Thanks!!!

**Comment by realdjpardis** [comment]
This is a great observation! We were able to find where this data was stored in our DB for these patients and so are going to be backfilling these fields with the new version. Attached please see the fill rates for the new version.
![image (2)](https://user-images.githubusercontent.com/57158121/82297927-3864cc80-9968-11ea-9e94-fdb24d3587a2.png)

**Comment by RSCOLOVE** [comment]
Thank you for maintaining this data and GitHub site.  We're continuing to explore how best to amplify physician and researcher insights with other data sources related to COVID-19 testing and treatment modalities.

**Comment by realdjpardis** [comment]
Thank you!

**Comment by OmKoren** [comment]
> This is a great observation! We were able to find where this data was stored in our DB for these patients and so are going to be backfilling these fields with the new version. Attached please see the fill rates for the new version.
> ![image (2)](https://user-images.githubusercontent.com/57158121/82297927-3864cc80-9968-11ea-9e94-fdb24d3587a2.png)

Great! Though it seems that the new batch has many missing vitals, more than the first 3 batches...
Anyway, awesome and helpful. Thank you!
